[general]
title = """

      ::::::::: ::::::::::::::    ::::::::::::::::::::::::: 
     :+:    :+::+:       :+:+:   :+:    :+:        :+:      
    +:+    +:++:+       :+:+:+  +:+    +:+        +:+       
   +#++:++#+ +#++:++#  +#+ +:+ +#+    +#+        +#+        
  +#+    +#++#+       +#+  +#+#+#    +#+        +#+         
 #+#    #+##+#       #+#   #+#+##+# #+#        #+#          
######### #############    #### #####     ###########     
"""

[database]
path = "sqlite:///database.db"

[logging]
level = "DEBUG"

[paths]
logs = "logs"
files = "uploads"

[files]
# File size limits in bytes
max_file_size = 104857600  # 100 MB
max_total_user_storage = 1073741824  # 1 GB

[endpoint]
# ws_client = "/client_endpoint"

[network]
host = "127.0.0.1"
port = 8000

reload = true

[network.rate_limit]
requests_per_second = 15
timeout_period = 60